name: CI

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Parsing assets:
        assets=( $(jq -r '.release.assets[] | @base64' "$GITHUB_EVENT_PATH") )
        echo Parsing done.
